routes/index.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory)

from models.user import User
from models.user_role import UserRole
from routes import current_user

main = Blueprint('index', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():
    u = current_user()
    return render_template("index.html", u=u)


@main.route("/login/view")
def login_view():
    u = current_user()
    return render_template("login.html", u=u)


@main.route("/register", methods=['POST'])
def register():
    # form = request.args
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    print('enter_login')
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        print('login_None')
        return redirect(url_for('coolwater_topic.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        print('login_session', session['user_id'])
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('coolwater_topic.index'))


@main.route('/profile')
def profile():
    u = current_user()
    if u.user_role is UserRole.guest:
        return redirect(url_for('index.login_view'))
    else:
        return render_template('profile.html', u=u)


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.find(id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', u=u)


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file = request.files['avatar']

    # ../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.profile'))


@main.route('/images/<filename>')
def image(filename):
    # 不要直接拼接路由，不安全，比如
    # open(os.path.join('images', filename), 'rb').read()
    return send_from_directory('images', filename)


@main.route("/logout")
def logout():
    session.clear()
    return redirect(url_for('index.login_view'))


@main.app_context_processor
def base_inject_user():
    return dict(base_inject_user=current_user())

routes/message.py
from flask_mail import Message, Mail
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.messages import Messages
from secret import admin_mail

main = Blueprint('mail', __name__)
mail = Mail()


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    form['receiver_id'] = int(form['receiver_id'])
    u = current_user()
    form['sender_id'] = u.id

    r = User.one(id=form['receiver_id'])
    m = Message(
        subject=form['title'],
        body=form['content'],
        sender=admin_mail,
        recipients=[r.email]
    )
    # mail.send(m)

    m = Messages.new(**form)
    return redirect(url_for('.index'))


@main.route('/')
def index():
    u = current_user()

    sent_mail = Messages.all(sender_id=u.id)
    received_mail = Messages.all(receiver_id=u.id)

    t = render_template(
        'mail/index.html',
        send=sent_mail,
        received=received_mail,
    )
    return t


@main.route('/view/<int:id>')
def view(id):
    mail = Messages.one(id=id)
    u = current_user()
    # if u.id == mail.receiver_id or u.id == mail.sender_id:
    if u.id in [mail.receiver_id, mail.sender_id]:
        return render_template('mail/detail.html', mail=mail)
    else:
        return redirect(url_for('.index'))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.board import Board
from routes import current_user

from models.topic import Topic


main = Blueprint('coolwater_topic', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    bs = Board.all()
    u = current_user()
    return render_template("topic/index.html", ms=ms, u=u, bs=bs, bid=board_id)


@main.route('/<int:id>')
def detail(id):
    # http://localhost:3000/topic/1
    m = Topic.get(id)
    u = current_user()
    # 不应该放在路由里面
    # m.views += 1
    # m.save()

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, u=u)


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    u = current_user()
    m = Topic.new(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
def new():
    bs = Board.all()
    return render_template("topic/new.html", bs=bs)


routes/user.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
    render_template,
    session,
)

from models.user import User
from models.reply import Reply
from models.topic import Topic
from routes import current_user

main = Blueprint('coolwater_user', __name__)


@main.route("/<username>", methods=["GET"])
def index(username):
    if User.guest().username != username:
        user_id = request.args['user_id']
        u = User.one(id=user_id)
        topics = Topic.all(user_id=u.id)
        replys = Reply.all()
        topics_reply = []
        for r in replys:
            topics_reply.append(Topic.one(id=r.topic_id))
        return render_template("user_history.html", u=u, topics=topics, topics_reply=topics_reply)
    else:
        return redirect(url_for('index.login_view'))


@main.route("/setting", methods=["POST"])
def setting():
    form = request.form.to_dict()
    u = current_user()
    # 旧密码一致 更新密码
    form['password'] = u.update_password(form)
    print('setting_form_dict', form)
    print('setting_salted_pass', u.update_password(form))
    User.update(id=u.id, **form)
    return redirect(url_for('index.profile'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link href="https://cdn.bootcss.com/pure/1.0.0/pure-min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/index.min.css">
    <title>{% block title %}{% endblock %} - bbs club</title>
    {% endblock %}
</head>
<body>

    {% block navbar %}
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="{{ url_for("coolwater_topic.index") }}">

          <img src="//o4j806krb.qnssl.com/public/images/cnodejs_light.svg">

      </a>

                <!-- <form id="search_form" class="navbar-search" action="/search">
                    <input id="q" name="q" class="search-query span3" value="" type="text">
                </form> -->
                <ul class="nav pull-right">
                    <li><a href="/">首页</a></li>
                    {% if base_inject_user.is_guest() %}
                    <li><a href="{{ url_for("index.login_view") }}">注册/登录</a></li>
                    {% endif %}
                    {% if not base_inject_user.is_guest() %}
                    <li><a href="{{ url_for("mail.index") }}">Mail</a></li>
                    <li><a href="{{ url_for("index.profile") }}">设置</a></li>
                    <li><a href="{{ url_for("index.logout") }}">登出</a></li>
                    {% endif %}
                </ul>
                <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
            </div>
        </div>
    </div>
    {% endblock %}

    {% block main %}

    {% block sidebar %}
    <div id="sidebar">

        <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="{{ url_for("coolwater_user.index", username=u.username, user_id=u.id) }}">
                            <img src="{{ u.image }}" title="{{ u.username }}">
                        </a>
                        <span class="user_name">
                            <a class="dark" href="{{ url_for("coolwater_user.index", username=u.username, user_id=u.id) }}">
                                {{ u.username }}
                            </a>
                        </span>

                        <div class="board clearfix">
                            <div class="floor">
                                <span class="big">积分: 25 </span>
                            </div>
                        </div>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            “

                                {{ u.signature }}

                            ”
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel">
            {% if not base_inject_user.is_guest() %}
            <div class="inner">
                <a href="{{ url_for('coolwater_topic.new') }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
            {% endif %}
        </div>
    </div>
    {% endblock %}

    {% endblock %}

    {% block footer %}
    <div id="footer">
        <div id="footer_main">
            <div class="links">
                <a class="dark" href="https://github.com/LiiangDD/bbs-demo">源码地址</a>
            </div>

            <div class="col_fade">

                <p>服务器赞助商为
                    <a href="http://www.ucloud.cn/?utm_source=zanzhu&amp;utm_campaign=cnodejs&amp;utm_medium=display&amp;utm_content=yejiao&amp;ytag=cnodejs_logo" target="_blank" class="sponsor_outlink" data-label="ucloud_bottom">
                        <img src="//dn-cnode.qbox.me/FuIpEaM9bvsZKnQ3QfPtBHWQmLM9" title="ucloud" alt="ucloud" width="92px">
                    </a> ，存储赞助商为
                    <a href="http://www.qiniu.com/?ref=cnode" target="_blank" class="sponsor_outlink" data-label="qiniu_bottom">
                        <img src="//dn-cnode.qbox.me/Fg0jtDIcTqVC049oVu5-sn6Om4NX" title="七牛云存储" alt="七牛云存储" width="115px">
                    </a> ，由
                    <a href="https://www.aliyun.com/product/nodejs?ref=cnode" target="_blank" class="sponsor_outlink" data-label="alinode_bottom">
                        <img src="//dn-cnode.qbox.me/FpMZk31PDyxkC8yStmMQL4XroaGD" title="alinode" alt="alinode" width="166px" height="54px">
                    </a>提供应用性能服务。
                </p>
                <p>新手搭建 Node.js 服务器，推荐使用无需备案的 <a href="https://www.digitalocean.com/?refcode=eba02656eeb3">DigitalOcean(https://www.digitalocean.com/)</a></p>
            </div>
        </div>
    </div>
    {% endblock %}
</body>
    {% block script %}
    {% endblock %}
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>两岁未来小站</title>
    <style>
        body {
            /* background: url(images/bg-masthead.jpg); */
        }
    </style>
    <link rel="stylesheet" href="/static/css/pure-min.css">
    <link rel="stylesheet" href="/static/css/marketing.css">
</head>
<body>
    <div class="splash-container">
        <div class="splash">
            <h1 class="splash-head">coolwater未来</h1>
            <p class="splash-subhead">
                <a href="https://github.com/LiiangDD/bbs-demo">Source Code/源代码</a>
            </p>
            <p>
                <a href="{{ url_for("coolwater_topic.index") }}" class="pure-button pure-button-primary">直接访问</a>
                {% if base_inject_user.is_guest() %}
                <a href="{{ url_for("index.login_view") }}" class="pure-button pure-button-primary">用户注册/登录</a>
                {% endif %}
            </p>
            <a href=http://www.beian.miit.gov.cn>粤ICP备18084425号</a>
        </div>
    </div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends "base.html" %}
    {% block title %}登录/注册{% endblock %}
</head>
<body>

    {% block main %}
    <div id="main">
                {% block sidebar %}
        <div id="sidebar">
          <div class="panel">
            <div class="header">
              <span class="col_fade">tips</span>
            </div>
            <div class="inner">
              <ol>
                <li><tt>1.按蓝色登录按钮登录，用户名密码已预设</tt></li>
                <li><tt>2.最右上角导航栏可完成用户的登录/登出</tt></li>
              </ol>
            </div>
          </div>
        </div>
        {% endblock %}
        <div id="content">
          <div class="panel">
            <div class="header">
              <ul class="breadcrumb">
                <li><a href="{{ url_for("coolwater_topic.index") }}">主页</a><span class="divider">/</span></li>
                <li class="active">登录注册页面</li>
              </ul>
            </div>
            <div class="inner">
                <form class="form-horizontal" method="post" action="{{ url_for('.register') }}">
                    <div class="control-group">
                        <label class="control-label">用户名</label>
                        <div class="controls">
                            <input type="text" class="input-xlarge" name="username">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">密码</label>
                        <div class="controls">
                            <input type="password" class="input-xlarge" name="password">
                        </div>
                    </div>
                    <div class="form-actions" method="post" action="{{ url_for('.register') }}">
                        <input type="submit" class="span-primary" value="注册">
                    </div>
                </form>
                <form class="form-horizontal" method="post" action="{{ url_for('.login') }}">
                    <div class="control-group">
                        <label class="control-label">用户名</label>
                        <div class="controls">
                            <input type="text" class="input-xlarge" name="username" value="test1">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">密码</label>
                        <div class="controls">
                            <input type="password" class="input-xlarge" name="password" value="123">
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="submit" class="span-primary" value="登录">
                    </div>
                </form>
            </div>
          </div>
        </div>

    </div>
    {% endblock %}

</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends "base.html" %}
    {% block title %}用户信息{% endblock %}
</head>
<body>

    {% block main %}
    <div id="main">
        {% block sidebar %} {{ super() }} {% endblock %}
        <div id="content">
          <div class="panel">
            <div class="header">
              <ul class="breadcrumb">
                <li><a href="/">主页</a><span class="divider">/</span></li>
                <li class="active">设置</li>
              </ul>
            </div>
            <div class="inner">
              <form id="setting_form" class="form-horizontal" action="{{ url_for("coolwater_user.setting") }}" method="post">
                <div class="control-group">
                  <label class="control-label" for="name">用户名</label>

                  <div class="controls">
                    <input class="input-xlarge" id="name" name="name" size="30" value="{{ u.username }}" type="text">
                  </div>
                </div>
                <div class="control-group">
                  <label class="control-label" for="signature">个性签名</label>

                  <div class="controls">
                    <textarea class="input-xlarge" id="signature" name="signature" size="30"></textarea>
                  </div>
                </div>
                <input id="action" name="action" value="change_setting" type="hidden">
                <input name="_csrf" value="aNia1AX8-CcLT1nsxukh183UU5H9y-EsTqtI" type="hidden">

                <div class="form-actions">
                  <input class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置" type="submit">
                </div>
              </form>
            </div>
          </div>

          <div class="panel">
            <div class="header">
              <span class="col_fade">更改密码</span>
            </div>
            <div class="inner">
              <form id="change_pass_form" class="form-horizontal" action="{{ url_for("coolwater_user.setting") }}" method="post">
                <div class="control-group">
                  <label class="control-label" for="old_pass">当前密码</label>

                  <div class="controls">
                    <input class="input-xlarge" id="old_pass" name="old_pass" size="30" type="password">
                  </div>
                </div>
                <div class="control-group">
                  <label class="control-label" for="new_pass">新密码</label>

                  <div class="controls">
                    <input class="input-xlarge" id="new_pass" name="new_pass" size="30" type="password">
                  </div>
                </div>
                <input id="action" name="action" value="change_password" type="hidden">
                <input name="_csrf" value="aNia1AX8-CcLT1nsxukh183UU5H9y-EsTqtI" type="hidden">

                <div class="form-actions">
                  <input class="span-primary submit_btn" data-loading-text="更改中.." value="更改密码" type="submit">
                </div>
              </form>
            </div>
          </div>

          <div class="panel">
            <div class="header">
              <span class="col_fade">上传头像</span>
            </div>
            <div class="inner">
              <div>
                  <form method="post"
                        action="{{ url_for('.avatar_add')}} "
                        enctype="multipart/form-data"
                  >
                      <input type="file" name="avatar">
                      <button type="submit">上传头像</button>
                  </form>
              </div>
          </div>
        </div>

    </div>
    {% endblock %}





</body>
</html>

templates/user_history.html
<!DOCTYPE html>
<html lang="en">
<head>
{% extends "base.html" %}
{% block title %}用户话题记录{% endblock %}

</head>

<body>

    {% block main %}
    <div id="main">
        {% block sidebar %} {{ super() }} {% endblock %}
        <div id="content">
            <div class="panel">
                <div class="header">
                    <ul class="breadcrumb">
                        <li><a href={{ url_for("coolwater_topic.index") }}>主页</a><span class="divider">/</span></li>
                    </ul>
                </div>
                <div class="inner userinfo">
                    <div class="user_big_avatar">
                        <img src="{{ u.image }}" class="user_avatar" title="{{ u.username }}">
                    </div>
                    <a class="dark">{{ u.username }}</a>

                    <div class="user_profile">
                        <ul class="unstyled">
                            <span class="big">25</span> 积分



                            <li>
                                <!-- <i class="fa fa-lg fa-fw fa-map-marker"></i>
                                <span class="dark">福建福州</span> -->
                            </li>


                            <li>
                                <!-- <i class="fa fa-lg fa-fw fa-github"></i>
                                <a class="dark" href="https://github.com/MeetTheBest" target="_blank">
                                    @MeetTheBest
                                </a> -->
                            </li>
                        </ul>
                    </div>
                    <!-- <p class="col_fade">注册时间 3 个月前</p> -->
                </div>
            </div>

            <div class="panel">
                <div class="header">
                    <span class="col_fade">最近创建的话题</span>
                </div>
                {% for t in topics %}
                <div class="cell">

                    <a class="user_avatar pull-left" href="{{ url_for('coolwater_user.index', username=t.user().username, user_id=t.user().id) }}">
                        <img src="{{ t.user().image }}" title="{{ t.title }}">
                    </a>

                    <span class="reply_count pull-left">
                            <span class="count_of_replies" title="回复数">
                                {{ t.replies() | count }}
                            </span>
                            <span class="count_seperator">/</span>
                            <span class="count_of_visits" title="点击数">
                                {{ t.views }}
                            </span>
                    </span>
                    <a class="last_time pull-right" href="/topic/{{ t.id }}">
                        <img class="user_small_avatar" src="">
                        <span class="last_active_time" data-created_time="{{ t.created_time }}"></span>
                    </a>
                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="/topic/{{ t.id }}" title="{{ t.title }}">
                            {{ t.title }}
                        </a>
                    </div>
                </div>
                {% endfor %}
                <div class="cell more">
                    <a class="dark" href="">查看更多»</a>
                </div>

            </div>

            <div class="panel">
                <div class="header">
                    <span class="col_fade">最近参与的话题</span>
                </div>
                {% for t in topics_reply %}
                <div class="cell">

                    <a class="user_avatar pull-left" href="{{ url_for('coolwater_user.index', username=t.user().username, user_id=t.user().id) }}">
                        <img src="{{ t.user().image }}" title="{{ t.title }}">
                    </a>

                    <span class="reply_count pull-left">
                        <span class="count_of_replies" title="回复数">
                            {{ t.replies() | count }}
                        </span>
                        <span class="count_seperator">/</span>
                        <span class="count_of_visits" title="点击数">
                            {{ t.views }}
                        </span>
                    </span>
                    <a class="last_time pull-right" href="/topic/{{ t.id }}">
                        <img class="user_small_avatar" src="{{ t.user().image }}">
                        <span class="last_active_time" data-created_time="{{ t.created_time }}"></span>
                    </a>
                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="/topic/{{ t.id }}" title="{{ t.title }}">
                            {{ t.title }}
                        </a>
                    </div>
                </div>
                {% endfor %}
                <div class="cell more">
                    <a class="dark" href="">查看更多»</a>
                </div>
            </div>
        </div>
    </div>
    <div id="backtotop" style="display: none; top: 343px; right: 0px;">回到顶部</div>
    <div id="sidebar-mask"></div>
    <script>
        // google analytics
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', "https://www.google-analytics.com/analytics.js", 'ga');

        ga('create', 'UA-41753901-5', 'auto');
        ga('send', 'pageview');
    </script>
    <script>
        var e = function (sel) {
            return document.querySelector(sel)
        }

        var es = function (sel) {
            return document.querySelectorAll(sel)
        }

        var registerTimer = function () {
            setInterval(function () {
                var times = es('.last_active_time')
                    for (var i = 0; i < times.length; i++) {
                        var t = times[i]
                        var time = Number(t.dataset.created_time)
                        var now = Math.floor(new Date() / 1000)
                        var delta = now - time
                        var s = `${delta} 秒前`
                        t.innerText = s
                    }
            }, 1000)
        }

        var __main = function () {
            registerTimer()
        }

        __main()
    </script>
    <div style="display:none;">
        <script src="//s95.cnzz.com/z_stat.php?id=1254020586&amp;web_id=1254020586" language="JavaScript"></script>
        <script src="https://c.cnzz.com/core.php?web_id=1254020586&amp;t=z" charset="utf-8" type="text/javascript"></script><a href="http://www.cnzz.com/stat/website.php?web_id=1254020586" target="_blank" title="站长统计">站长统计</a>
    </div>
    {% endblock %}


</body>

</html>