models/topic.py
import time

from sqlalchemy import String, Integer, Column, Text, UnicodeText, Unicode, desc

from models.base_model import SQLMixin, SQLBase
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, SQLBase):
    __tablename__ = 'Topic'
    views = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)
    board_id = Column(Integer, nullable=False)

    @classmethod
    def new(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(**form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

    # 改写继承的父类方法 按时间倒序获取topic数组
    @classmethod
    def all(cls, **kwargs):
        ms = cls.query.filter_by(**kwargs).order_by(desc(cls.created_time)).all()
        return ms

routes/reply.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.messages import Messages
from models.user import User
from routes import current_user

from models.reply import Reply


main = Blueprint('coolwater_reply', __name__)


def users_from_content(content):
    # 内容 @123 内容
    # 如果用户名含有空格 就不行了 @name 123
    # 'a b c' -> ['a', 'b', 'c']
    parts = content.split()
    users = []

    for p in parts:
        if p.startswith('@'):
            username = p[1:]
            u = User.one(username=username)
            print('users_from_content <{}> <{}> <{}>'.format(username, p, parts))
            if u is not None:
                users.append(u)

    return users


def send_mails(sender, receivers, content):
    print('send_mail', sender, receivers, content)
    for r in receivers:
        form = dict(
            title='你被 {} AT 了'.format(sender.username),
            content=content,
            sender_id=sender.id,
            receiver_id=r.id
        )
        Messages.new(**form)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()

    content = form['content']
    users = users_from_content(content)
    send_mails(u, users, content)
    form = form.to_dict()
    m = Reply.new(form, user_id=u.id)
    return redirect(url_for('coolwater_topic.detail', id=m.topic_id))


routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.board import Board
from routes import current_user

from models.topic import Topic


main = Blueprint('coolwater_topic', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    bs = Board.all()
    u = current_user()
    return render_template("topic/index.html", ms=ms, u=u, bs=bs, bid=board_id)


@main.route('/<int:id>')
def detail(id):
    # http://localhost:3000/topic/1
    m = Topic.get(id)
    u = current_user()
    # 不应该放在路由里面
    # m.views += 1
    # m.save()

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, u=u)


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    u = current_user()
    m = Topic.new(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
def new():
    bs = Board.all()
    return render_template("topic/new.html", bs=bs)


routes/user.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
    render_template,
    session,
)

from models.user import User
from models.reply import Reply
from models.topic import Topic
from routes import current_user

main = Blueprint('coolwater_user', __name__)


@main.route("/<username>", methods=["GET"])
def index(username):
    if User.guest().username != username:
        user_id = request.args['user_id']
        u = User.one(id=user_id)
        topics = Topic.all(user_id=u.id)
        replys = Reply.all()
        topics_reply = []
        for r in replys:
            topics_reply.append(Topic.one(id=r.topic_id))
        return render_template("user_history.html", u=u, topics=topics, topics_reply=topics_reply)
    else:
        return redirect(url_for('index.login_view'))


@main.route("/setting", methods=["POST"])
def setting():
    form = request.form.to_dict()
    u = current_user()
    # 旧密码一致 更新密码
    form['password'] = u.update_password(form)
    print('setting_form_dict', form)
    print('setting_salted_pass', u.update_password(form))
    User.update(id=u.id, **form)
    return redirect(url_for('index.profile'))

templates/topic/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends "base.html" %}

    {% block head %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link href="//cdn.bootcss.com/prism/1.8.0/themes/prism.css" rel="stylesheet">
    {% endblock %}
    {% block title %}{{ topic.title }}{% endblock %}
</head>
<body>
    {% block main %}
    <div id="main">
        {% block sidebar %} {{ super() }} {% endblock %}
        <div id="content">
            <div class='panel'>
                <div class='header topic_header'>
                    <span class="topic_full_title">
            			{{ topic.title }}
                  	</span>
                    <div class="changes">
                        <span>
                            发布于 2 天前
                        </span>
                        <span>
                            <a class="" href="{{ url_for("coolwater_user.index", username=topic.user().username, user_id=topic.user().id) }}">
                            作者 {{ topic.user().username }}
                            </a>
            	        </span>
                        <span>
              	            {{ topic.views }} 次浏览
            	           </span>
                        <span>
                            来自 问答
                        </span>
                    </div>
                </div>

                <div class='inner topic'>
                    <div class='topic_content'>
                        <div class="markdown-text">{{ topic.content }}</div>
                    </div>
                </div>
            </div>
        </div>
        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>
                    <!-- 过滤器 -->
                    {{ topic.replies() | count }} 回复
                </span>
            </div>
            {% for r in topic.replies() %}
            {% set u = r.user() %}
            <div class='cell reply_area reply_item'>
                <div class='user_info'>
                    <a class='dark reply_author'>
                        {{ u.username }}
                    </a>
                    <a class="reply_time">
                        {{ loop.index }}楼 / {{ loop.length }}楼 •
                        <span class="gua-time" data-created_time="{{ r.created_time }}"></span>
                    </a>
                </div>
                <div class='user_action'>
                        <span>
                            <i class="fa up_btn
                              fa-thumbs-o-up
                              invisible" title="喜欢"></i>
                            <span class="up-count">
                            </span>
                        </span>
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text">{{ r.content }}</div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div>
            {% if not u.is_guest()%}
            <form class="pure-form pure-form-stacked" action="{{ url_for('coolwater_reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <textarea name="content"></textarea>
                <button class="pure-button pure-button-primary">添加回复</button>
            </form>
            {% endif %}
        </div>
    </div>
    <script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
    <script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
    <script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
    <script>
        var e = function (sel) {
            return document.querySelector(sel)
        }

        var es = function (sel) {
            return document.querySelectorAll(sel)
        }

        var markContents = function () {
            // markdown -> html 的处理放在高亮前面
            // 因为高亮是针对 html 格式的
            // lang -> language 不需要转 prism 自动转了
            var contentDivs = es('.markdown-text')
            for (var i = 0; i < contentDivs.length; i++) {
                var contentDiv = contentDivs[i]
                console.log('pre marked', contentDiv.textContent, contentDiv.innerHTML)
                var content = marked(contentDiv.textContent)
                console.log('after marked', content)
                contentDiv.innerHTML = content
            }
        }

        var highlight = function() {
             // 自动加载对应的语言 不然要手动加入各个语言的 js
            Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
        }

        var registerTimer = function () {
            setInterval(function () {
                var times = es('.gua-time')
                for (var i = 0; i < times.length; i++) {
                    var t = times[i]
                    var time = Number(t.dataset.created_time)
                    var now = Math.floor(new Date() / 1000)
                    var delta = now - time
                    var s = `${delta} 秒前`
                    t.innerText = s
                }
            }, 1000)
        }

        var __main = function () {
            markContents()
            highlight()
            registerTimer()
        }

        __main()

    </script>
    {% endblock %}
</body>
</html>

templates/topic/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends "base.html" %}
    {% block title %}话题列表{% endblock %}
</head>
<body>
    {% block main %}
    <div id="main">
        {% block sidebar %} {{ super() }} {% endblock %}
        <div id="content">
            <div class="panel">
                <div class="header">
                    <a href="{{ url_for("coolwater_topic.index") }}"
                       class="topic-tab current-tab">
                        全部的帖子
                    </a>

                    {% for b in bs %}
                    <a href="/topic?board_id={{ b.id }}"
                       class="topic-tab current-tab">
                        {{ b.title }}
                    </a>
                    {% endfor %}
                </div>
                <div class="inner post">
                    <div class="topic_list">
                        {% for t in ms %}
                        <div class="cell">
                            <div class="topic_title_wrapper">
                                <a class="user_avatar pull-left" href="{{ url_for('coolwater_user.index', username=t.user().username, user_id=t.user().id) }}">
                                    <img src="{{ t.user().image }}" title="{{ t.user().username }}">
                                </a>
                                <a class="topic_title" href="{{ url_for('coolwater_topic.detail', id=t.id) }}">
                                    {{ t.title }}
                                </a>
                                <span>{{ t.replies() | count }} / {{ t.views }}</span>
                                {# count(t.replies()) #}
                                {# <span>{{ t.reply_count() }} / {{ t.views }}</span> #}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</body>

</html>

templates/topic/new.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% extends "base.html" %}

    {% block head %}
    {{ super() }}
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
    {% endblock %}
    {% block title %}发布话题{% endblock %}
</head>

<body>
    {% block main %}
    <div id="main">
        {% block sidebar %}
        <div id="sidebar">
          <div class="panel">
            <div class="header">
              <span class="col_fade">Markdown 语法参考</span>
            </div>
            <div class="inner">
              <ol>
                <li><tt>### 单行的标题</tt></li>
                <li><tt>**粗体**</tt></li>
                <li><tt>`console.log('行内代码')`</tt></li>
                <li><tt>```js\n code \n```</tt> 标记代码块</li>
                <li><tt>[内容](链接)</tt></li>
                <li><tt>![文字说明](图片链接)</tt></li>
              </ol>
              <span><a href="https://segmentfault.com/markdown" target="_blank">Markdown 文档</a></span>
            </div>
          </div>

          <div class="panel">
            <div class="header">
              <span class="col_fade">话题发布指南</span>
            </div>
            <div class="inner">
              <ol>
                <li>尽量把话题要点浓缩到标题里</li>
                <li>代码含义和报错可在 <a href="http://segmentfault.com/t/node.js">SegmentFault</a> 提问</li>
              </ol>
            </div>
          </div>
        </div>
        {% endblock %}
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <span class="tab-selector">选择版块：</span>
                            <select name="board_id" id="board" required>
                                {% for b in bs %}
                                    {% if bid == b.id %}
                                        <option value="{{ b.id }}" selected >{{ b.title }}</option>
                                    {% else %}
                                        <option value="{{ b.id }}" >{{ b.title }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                            <div class='markdown_editor in_editor'>
                                <div class='markdown_in_editor'>
                                    <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                    <div class='editor_buttons'>
                                        <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</body>
{% block script %}
<script>
    (sfunction() {
        var editor = new Editor();
        editor.render($('.editor')[0]);
    })();
</script>
{% endblock %}

</html>